id = "Erythtini.ReelBonusSpy"
name = "ReelBonusSpy"
description = "Tells you when the 1.1x catch rate bonus from recently reeling results in a catch (or when not having it results in a miss)."
version = "1.0.0"
homepage = "https://github.com/TornadoToss/Webfishing-Mods/tree/main/ReelBonusSpy"
author = "Erythtini"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./ReelBonusSpy/Erythtini.ReelBonusSpy.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
